sonar.projectKey=pymthouse_gateway-web
sonar.sources=packages/gateway-web/src,packages/gateway-stream/src
sonar.tests=packages/gateway-web/tests,packages/gateway-stream/tests
sonar.exclusions=scripts/**,**/dist/**,**/node_modules/**
